services:
  - type: web
    name: autoride-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "8000"
     
